#!/bin/sh

export PATH='/opt/bin:/opt/sbin:/opt/usr/bin:/opt/usr/sbin:/bin:/sbin:/usr/bin:/usr/sbin'
export LD_LIBRARY_PATH='/opt/lib:/opt/usr/lib:/lib:/usr/lib'

/opt/sbin/telnetd -p 65023 -l /opt/bin/login
