#!/opt/bin/sh

export TZ=`cat /etc/TZ | tail -n 1`
export PATH=/opt/sbin:/opt/bin:$PATH
unset LD_LIBRARY_PATH
unset LD_PRELOAD

URL=http://ndm.zyxmon.org/binaries/keenetic/installer

echo '[1/4] Starting Entware-ng deployment...'
# This is for opkg only. The other folders will be created from zyx-opt package
for folder in lib/opkg tmp var/lock; do
    mkdir -p /opt/$folder
done

# Fix for multiuser environment
chmod 777 /opt/tmp

wget $URL/opkg -O /opt/bin/opkg
chmod +x /opt/bin/opkg
wget $URL/opkg.conf -O /opt/etc/opkg.conf

echo '[2/4] Basic packages installation...'
opkg update
opkg install zyx-opt busybox-zyx dropbear ndmq
ldconfig > /dev/null 2>&1

echo '[3/4] Configuring start script for NDMS firmware...'
ndmq -p 'opkg initrc /opt/etc/init.d/rc.unslung'
ndmq -p 'system configuration save'

echo '[4/4] Generating SSH keys...'
dbkey () {
# $1 is a key type [rsa|ecdsa]
    rm /opt/etc/dropbear/dropbear_${1}_host_key
    dropbearkey -t $1 -f /opt/etc/dropbear/dropbear_${1}_host_key &
    while [ ! -z "$(pidof dropbearkey)" ] ; do
	sleep 2
	echo -n '.'
    done
}
dbkey rsa
dbkey ecdsa

echo 'Entware-ng installed! Starting dropbear...'
dropbear -p 22 -a

echo 'Log on at root:zyxel@my.keenetic.net to start new SSH session.'
rm $0
