#!/opt/bin/sh

export TZ=`cat /etc/TZ | tail -n 1`
export PATH=/opt/sbin:/opt/bin:$PATH
unset LD_LIBRARY_PATH
unset LD_PRELOAD

URL=http://ndm.zyxmon.org/binaries/keenetic/installer

echo 'Starting Entware-ng deployment...'
echo '[1/3] Deploying opkg package manager...'
# This is for opkg only. The other folders will be created from zyx-opt package
for folder in lib/opkg tmp var/lock; do
    mkdir -p /opt/$folder
done

# Fix for multiuser environment
chmod 777 /opt/tmp

wget $URL/opkg -O /opt/bin/opkg
chmod +x /opt/bin/opkg
wget $URL/opkg.conf -O /opt/etc/opkg.conf

echo '[2/3] Basic packages installation...'
opkg update
opkg install zyx-opt busybox-zyx dropbear ndmq
ldconfig > /dev/null 2>&1

echo '[3/3] Entware-ng installed! Starting dropbear...'
dropbear -p 22 -a

echo 'Log on at root:zyxel@my.keenetic.net to start new SSH session.'
rm $0
