#!/bin/sh

SWAPFILE="/opt/.swapfile"
export PATH=/opt/bin:/opt/sbin:/sbin:/usr/sbin:/bin:/usr/bin


start() {
	if [ -f /proc/swaps ] && [ `wc -l < /proc/swaps` -lt 2 ]; then
		swapon $SWAPFILE 2> /dev/null
	fi
}
    
stop() {
	if `grep -q $SWAPFILE < /proc/swaps`; then
		swapoff $SWAPFILE 2> /dev/null
	fi
}
	
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 1
        start
	;;
    *)
	echo "Usage: $0 {start|stop}"
	;;
esac
